import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { SPARK_TELEGRAM_PERSONA_SNIPPET } from '../src/generated/sparkPersonaSnippet';

function test(name: string, fn: () => void): void {
  try {
    fn();
    console.log(`ok - ${name}`);
  } catch (error) {
    console.error(`not ok - ${name}`);
    throw error;
  }
}

function renderCanonicalPersona(): string {
  const sparkCharacterRoot = process.env.SPARK_CHARACTER_ROOT || 'C:\\Users\\USER\\Desktop\\spark-character';
  const python = process.env.PYTHON || 'python';
  const result = spawnSync(
    python,
    [
      '-c',
      'import sys; from spark_character import load_persona; sys.stdout.buffer.write(load_persona(surface="telegram").text.encode("utf-8"))',
    ],
    {
      cwd: sparkCharacterRoot,
      env: {
        ...process.env,
        PYTHONPATH: path.join(sparkCharacterRoot, 'src'),
      },
      encoding: 'utf8',
    }
  );
  assert.equal(result.status, 0, result.stderr || result.stdout);
  return result.stdout;
}

test('generated persona snippet matches spark-character render byte for byte', () => {
  assert.equal(SPARK_TELEGRAM_PERSONA_SNIPPET, renderCanonicalPersona());
});

test('generated persona snippet carries generated-file header', () => {
  const source = readFileSync(path.join(__dirname, '..', 'src', 'generated', 'sparkPersonaSnippet.ts'), 'utf8');
  assert.match(source, /@generated by spark-character/);
  assert.match(source, /Do not edit by hand/);
});
