/**
 * Deterministic voice post-fixes applied to every Telegram reply.
 *
 * Mirrors spark_character.output_sanitizer (Python) so the same rule
 * applies whether a reply was generated by the Node bot directly or
 * by the Python builder bridge. Currently scoped to the em-dash
 * family because production telemetry showed ~50% of replies leaked
 * em dashes despite the persona forbidding them, and prompt-layer
 * fixes were not enough.
 */

import { redactText } from './redaction';

const EM_DASH_FAMILY = [
  '\u2014', // em dash
  '\u2013', // en dash
  '\u2012', // figure dash
  '\u2015', // horizontal bar
  '\u2212', // minus sign
];
export const TELEGRAM_HARD_MESSAGE_LIMIT = 4096;
export const TELEGRAM_SAFE_MESSAGE_LIMIT = 3600;

function isDashPunctuation(ch: string): boolean {
  return ch !== '-' && (/\p{Dash_Punctuation}/u.test(ch) || ch === '\u2212');
}

export function stripFormatControls(text: string): string {
  if (!text) return text;
  return text.replace(/\p{Cf}/gu, '');
}

export function replaceEmDashes(text: string, replacement: string = ' - '): string {
  if (!text) return text;
  const trimLeft = replacement.startsWith(' ');
  const trimRight = replacement.endsWith(' ');
  const out: string[] = [];
  for (let index = 0; index < text.length; index += 1) {
    const ch = text[index];
    if (isDashPunctuation(ch) || EM_DASH_FAMILY.includes(ch)) {
      if (trimLeft && out.length > 0 && (out[out.length - 1] === ' ' || out[out.length - 1] === '\t')) {
        out.pop();
      }
      out.push(replacement);
      if (trimRight && index + 1 < text.length && (text[index + 1] === ' ' || text[index + 1] === '\t')) {
        index += 1;
      }
    } else {
      out.push(ch);
    }
  }
  return out.join('');
}

export function stripMarkdownEmphasis(text: string): string {
  if (!text) return text;
  return text
    .replace(/\*\*\*([^*\n][\s\S]*?[^*\n])\*\*\*/g, '$1')
    .replace(/\*\*([^*\n][\s\S]*?[^*\n])\*\*/g, '$1')
    .replace(/__([^_\n][\s\S]*?[^_\n])__/g, '$1');
}

export function rewriteSpawnerSurfaceStandaloneQuestion(text: string): string {
  if (!text) return text;
  const lower = text.toLowerCase();
  const mentionsSpawnerSurface =
    lower.includes('spawner') &&
    (lower.includes('kanban') || lower.includes('canvas') || lower.includes('mission control'));
  if (!mentionsSpawnerSurface || !lower.includes('standalone')) return text;

  return text
    .replace(
      /\n?\s*[-*]?\s*Are you thinking this (?:runs locally as|should run locally as|should be) a standalone (?:page|app|tool),\s*or lives? inside the existing Spawner UI routes\?\s*$/i,
      '\n\nSince this lives inside the existing Spawner UI routes, the useful question is: which surface should we tighten first - Kanban state accuracy, Canvas execution state, or Telegram relay messaging?'
    )
    .replace(
      /\n?\s*[-*]?\s*Should this be a standalone (?:page|app|tool),\s*or live inside the existing Spawner UI routes\?\s*$/i,
      '\n\nSince this lives inside the existing Spawner UI routes, the useful question is: which surface should we tighten first - Kanban state accuracy, Canvas execution state, or Telegram relay messaging?'
    );
}

export function collapseTelegramHorizontalRules(text: string): string {
  if (!text) return text;
  return text
    .replace(/(?:^|\n)[ \t]*(?:[-*_]){3,}[ \t]*(?=\n|$)/g, '\n\n')
    .replace(/\n{3,}/g, '\n\n');
}

export function sanitizeOutbound(text: string): string {
  return redactText(
    rewriteSpawnerSurfaceStandaloneQuestion(
      collapseTelegramHorizontalRules(stripMarkdownEmphasis(replaceEmDashes(stripFormatControls(text))))
    )
  );
}

function splitExistingNumberedChunks(text: string, maxChars: number): string[] | null {
  const parts = text
    .trim()
    .split(/\n\s*(?=\(\d+\/\d+\)\s)/)
    .map((part) => part.trim())
    .filter(Boolean);
  if (parts.length <= 1) return null;
  if (parts.every((part) => part.length <= maxChars)) {
    return parts;
  }
  return parts.flatMap((part) => splitTelegramText(part, maxChars));
}

function findTelegramSplitIndex(window: string, maxChars: number): number {
  const minimumUsefulSplit = Math.floor(maxChars * 0.45);
  for (const boundary of ['\n\n', '\n', '. ', '; ', ' ']) {
    const index = window.lastIndexOf(boundary);
    if (index > minimumUsefulSplit) {
      return index + boundary.length;
    }
  }
  return maxChars;
}

export function splitTelegramText(text: string, maxChars = TELEGRAM_SAFE_MESSAGE_LIMIT): string[] {
  if (!text) return [''];
  const existingChunks = splitExistingNumberedChunks(text, maxChars);
  if (existingChunks) {
    return existingChunks;
  }
  if (text.length <= maxChars) return [text];

  const chunks: string[] = [];
  let remaining = text.trim();

  while (remaining.length > maxChars) {
    const window = remaining.slice(0, maxChars + 1);
    const cut = findTelegramSplitIndex(window, maxChars);
    chunks.push(remaining.slice(0, cut).trim());
    remaining = remaining.slice(cut).trim();
  }

  if (remaining) {
    chunks.push(remaining);
  }
  return chunks.length ? chunks : [''];
}

export function sanitizeAndSplitTelegramText(text: string, maxChars = TELEGRAM_SAFE_MESSAGE_LIMIT): string[] {
  return splitTelegramText(sanitizeOutbound(text), maxChars);
}
